BugFix: Logme causes error on empty string filenames
Error text:
Traceback (most recent call last):
  File "/home/dacre/vcf_simplify/vcf_simplify.py", line 245, in <module>

  File "/home/dacre/vcf_simplify/vcf_simplify.py", line 241, in main
    if line:
  File "/usr/local/lib/python3.3/multiprocessing/pool.py", line 562, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'name'

I think this came from the getattr(... 'name') string in _logme, I have
fixed this now.